export default interface Resumo {
    volumes: string;
    volumesR: string;
    volumesN: string;
    gradesValidas: string;
    pesoR: string;
    cubagemR: string;
    pesoN: string;
    cubagemN: string;
    pesoT: string;
    cubagemT: string;
    prevRepo: string;
    escolasAtendidasN: string;
    escolasAtendidasR: string;
    expedidos: string;
    aExpedir: string;
    gradesRepo: string;
    expRepo: string;
    previstoN: string;
    aExpRepo: string;
    previstoT: string;
    gradesT: string;
    expedidosT: string;
    aExpedirT: string;
    escolasAtendidasT: string,
    escolasTotaisN: string;
    escolasTotaisR: string;
    escolasTotaisT: string;
    percErr: string;
    ids: number[];
}
